export interface TonDocCategory { type: 'category'; title: string; }
export interface TonDocEntry { type: 'entry'; fragment: string; title: string; category: string; description: string; method?: 'GET'; path?: string; request?: string; response?: string; }
export type TonDocItem = TonDocCategory | TonDocEntry;
const guide = (fragment: string, title: string, category: string, description: string): TonDocEntry => ({type:'entry',fragment,title,category,description});
const api = (fragment: string, title: string, category: string, path: string, description: string): TonDocEntry => ({type:'entry',fragment,title,category,path,method:'GET',description});
const link = (url: string, title: string) => `<a href="${url}" target="_blank" rel="noopener noreferrer">${title}</a>`;
export const tonGuideData: TonDocItem[] = [
  {type:'category',title:'TON basics'},
  guide('masterchain-and-shards','What do masterchain and shard blocks mean?','Network','<p>The masterchain holds global configuration and references shardchain states. Most user accounts live in the basechain, which can be divided into shards. A block is identified by its workchain, shard and sequence number together; a sequence number alone is not a network-wide block height.</p><p>The top strip shows basechain blocks. Open the search menu and choose Masterchain under SELECTED to view masterchain blocks. Choose a shard when several are active. Open a block to inspect its transactions; masterchain blocks also link their referenced shards.</p>'),
  guide('transactions-and-messages','How are transactions, messages and traces related?','Transactions',`<p>A transaction records one account processing a message or a system operation. Messages connect accounts; processing an incoming message may create outgoing messages and further transactions. A trace follows those linked transactions.</p><p>Use the transaction page for local execution, messages for transfers between contracts, and the trace for the wider operation. ${link('https://docs.ton.org/start-here','TON fundamentals')}.</p>`),
  guide('logical-time','What is logical time?','Transactions','<p>Logical time (LT) orders transactions and messages. It is separate from the Unix timestamp shown as the transaction date. Account history uses LT as its pagination cursor; preserve it as an exact integer string.</p>'),
  guide('fees-and-phases','Where did the fee go?','Transactions','<p>Execution can include storage, credit, compute, action and bounce phases. The transaction page shows total fees and the recorded phase details, including gas use, forwarding costs and exit codes. A failed operation can still pay fees.</p><p>GRAM is TON’s native currency and uses 9 decimal places: 1 GRAM = 1,000,000,000 nanograms. A message value and the transaction fee describe different amounts.</p>'),
  guide('bounce-and-failure','What does bounced or failed mean?','Transactions',`<p>A bounced message returns a response when a bounceable message cannot be processed under the applicable rules. It is a separate message with its own value and costs. Check the transaction result, compute and action results, and outgoing messages together.</p><p>A confirmed transaction can have failed execution. One successful transaction also does not establish that every later transaction in its trace succeeded. ${link('https://docs.ton.org/resources/pdfs/tblkch.pdf','TON blockchain specification')}.</p>`),
  guide('confirmation','Is confirmation the same as a complete operation?','Transactions','<p>Confirmation means the transaction is included in its block. A multi-contract operation can involve additional transactions and messages. Inspect the full trace and final recipient rather than treating the first transaction as the whole transfer.</p>'),
  {type:'category',title:'Wallets and contracts'},
  guide('wallets-and-state','What does an account page show?','Accounts','<p>Accounts show their GRAM balance, state, last activity and detected contract interfaces. History groups recognized actions; Transactions lists account transactions. Jettons and NFTs have separate tabs.</p><p>The Contract tab contains state, code and data, read-only methods, and available staking, multisig, subscription and DeFi records. Expand Account details for additional fields and extra currencies.</p>'),
  guide('addresses-and-dns','Why can the same account have different addresses?','Accounts','<p>TON accounts can be written as a raw workchain and hexadecimal account ID or a user-friendly address. Bounceability and network flags can change the user-friendly representation without changing the underlying account.</p><p>Search accepts TON addresses and .ton names. DNS resolution links to the resolved account; a domain name is not a substitute for checking the account address.</p>'),
  guide('contract-methods','Can I read a smart contract?','Contracts','<p>Select a listed getter in the Contract tab and supply its arguments when needed. Reads return a result without signing a transaction. Arguments may be comma-separated strings or a JSON array of strings; preserve large integers as strings.</p><p>Account details preserve code, data and storage fields. Inspection shows recognized interfaces and available compiler information.</p>'),
  guide('validators','What does the validators page show?','Network','<p>The validators page shows the election timestamps, total and minimum stake, and participating validator accounts, stakes and ADNL addresses. These fields describe the displayed election data; an address holding stake is not automatically the producer of a particular block.</p>'),
  {type:'category',title:'Jettons and NFTs'},
  guide('jettons','How do jettons work?','Jettons',`<p>A jetton has a master contract and individual jetton-wallet contracts for holders. Identify it by the master address, not its name or symbol. The jetton page shows supply, decimals, administration and holders.</p><p>Display balances using the jetton’s own decimals. Do not assume every jetton has 9 decimals. ${link('https://docs.ton.org/contracts/standard/tokens/jettons/overview','Jetton standard')}.</p>`),
  guide('scaled-jettons','Why can a jetton’s displayed balance differ from its on-chain amount?','Jettons',`<p>Some jettons use a display multiplier. Current wallet balances, holder balances and total supply apply that ratio with exact rounding, then the token’s decimals. Expand Amount details to see the on-chain amount, raw units and ratio.</p><p>Historical transfers retain their recorded on-chain quantity; a current multiplier is not evidence of the multiplier at that time. ${link('https://github.com/ton-blockchain/TEPs/blob/master/text/0526-scaled-ui-jettons.md','Scaled UI jetton standard')}.</p>`),
  guide('nft-identity','What identifies an NFT?','NFTs','<p>The NFT item’s contract address is its identity. Its collection, owner and item index are separate fields. Collection membership verification checks the item’s relationship to a collection; it does not establish that its image, name or seller is trustworthy.</p><p>Item details show the exact index when confirmed by the NFT contract. A display number in an NFT’s name need not equal its on-chain index.</p>'),
  guide('nft-metadata','Where do images and attributes come from?','NFTs',`<p>TEP-64 supports on-chain, off-chain and combined metadata. The NFT page displays names, descriptions, images and attributes, with the full metadata available to expand. Media or metadata hosted elsewhere can change or become unavailable.</p><p>Open animations explicitly from the item page. Missing media does not erase the NFT’s contract or ownership record. ${link('https://github.com/ton-blockchain/TEPs/blob/master/text/0064-token-data-standard.md','Token metadata standard')}.</p>`),
  guide('nft-sales','Why is an NFT owned by a sale contract?','NFTs','<p>A listed NFT may be held by a marketplace sale contract. Wallet NFT lists include recognized indirect sale ownership. The item page separates the on-chain owner, seller, sale contract and price currency.</p><p>A sale listing is not a completed transfer. Use transfer history to follow changes, and the collection page to browse its items.</p>'),
  guide('telegram-collectibles','Are all Telegram gifts visible on-chain?','Collectibles',`<p>No. A gift must exist as a TON NFT to have an on-chain item address and ownership record here. Telegram gifts, collectible usernames and numbers can have associated TON NFTs, but a Telegram profile or ordinary username alone does not prove wallet ownership.</p><p>A collectible may be displayed on a Telegram profile while its owner remains a TON wallet. Check its item address, collection and current owner. ${link('https://core.telegram.org/api/gifts','Telegram collectible gifts')}.</p>`),
  guide('nft-pagination','How do I see all the NFTs in an account or collection?','NFTs','<p>Use Load more below the NFT list to continue through the collection or wallet. The NFTs tab includes each returned item separately, with its full name and link to item details. A wallet’s NFT collection and its transaction history are independent lists.</p>'),
  guide('trust-and-identity','What do recognition labels mean?','Assets','<p>Collection membership, trust classification and marketplace approvals are distinct facts. Recognized names and images are not ownership proofs. Compare contract addresses and collection links before treating two similarly named assets as the same token.</p>'),
  {type:'category',title:'Using tx.taxi'},
  guide('automatic-routing','How does automatic routing work?','Search','<p>Paste an address, transaction hash, message hash, block number or .ton name into search. Automatic Routing lets the taxi find its chain. Choosing a native explorer keeps that chain’s search available; View Hub returns to tx.taxi.</p>'),
  guide('updates','What does Updates delayed mean?','Live data','<p>The last available data remains visible while fresh updates are delayed. Retry an unavailable section to load it again. An empty list and an unavailable list are different states.</p>'),
  guide('wallet-support','Can tx.taxi reverse a transaction?','Support','<p>tx.taxi displays public chain data. It cannot sign transactions, access private keys or reverse a transfer. For wallet or exchange account support, contact the service that submitted the operation.</p>'),
];
export const tonRestData: TonDocItem[] = [
  {type:'category',title:'Conventions'},
  guide('api-values','Values and pagination','Reference','<p>All routes below use GET. Precision-sensitive integers are decimal strings; parse them with arbitrary-precision arithmetic. GRAM balances and fees are nanograms. Jetton amounts use their declared decimals.</p><p>Paginated responses include <code>_paging</code>. Continue only while <code>hasMore</code> is true, using <code>nextOffset</code>, <code>nextBeforeLt</code> or <code>nextBefore</code> for the matching endpoint. List limits are capped at 100; block lists at 16.</p><p><code>_meta.observedAt</code> identifies the observation time and <code>_meta.stale</code> marks retained data. HTTP 400 means invalid input, 404 means not found, and 503 means temporarily unavailable.</p>'),
  {type:'category',title:'Network and blocks'},
  api('get-dashboard','Network overview','Network','/api/ton/dashboard','<p>Returns the selected workchain and shard, recent blocks, observed history, observation time and stale state. The default is the basechain. Use <code>workchain=-1</code> for the masterchain, or <code>workchain=0&amp;shard=...</code> for an active basechain shard. <code>activeShards</code> lists available shards; <code>masterchainHead</code> is the network masterchain head.</p>'),
  api('get-blocks','Blocks','Blocks','/api/ton/blocks?workchain=0&limit=8','<p>Returns blocks from one workchain and shard in descending sequence order. The default is the basechain; use <code>workchain=-1</code> for masterchain blocks. Continue with <code>before=_paging.nextBefore</code> and retain <code>workchain</code> and <code>shard</code> from the response; the boundary is exclusive. Pagination stops at a shard split or merge.</p>'),
  api('get-block','Block details','Blocks','/api/ton/block/:id','<p>Use a masterchain sequence number or the full <code>(workchain,shard,seqno)</code> identifier. Returns hashes, timestamps, logical times, references and value-flow fields.</p>'),
  api('get-block-transactions','Block transactions','Blocks','/api/ton/block/:id/transactions','<p>Returns the transactions included in the specified block.</p>'),
  api('get-block-shards','Masterchain shard references','Blocks','/api/ton/block/:id/shards','<p>Use a masterchain sequence number or masterchain block identifier. Returns the corresponding shard references.</p>'),
  api('get-network-transactions','Network transactions','Transactions','/api/ton/network-transactions?limit=20','<p>Returns transactions across the shards in one masterchain interval. Continue within that interval using <code>master_seqno=_paging.masterSeqno</code> and <code>offset=_paging.nextOffset</code>. When <code>nextOffset</code> is null, continue with <code>before=_paging.nextBefore</code> instead. Limits are capped at 50.</p>'),
  api('get-transactions','Masterchain transactions','Transactions','/api/ton/transactions','<p>Returns transactions from one masterchain block. Continue with <code>before=_paging.nextBefore</code>. These are masterchain transactions, not all transactions across every shard.</p>'),
  api('get-validators','Validators','Network','/api/ton/validators','<p>Returns validator election information, stake amounts and validator entries.</p>'),
  api('get-dns','Domain details','Network','/api/ton/dns/:domain','<p>Domain identity, expiry and linked NFT. Append <code>/resolve</code> for wallet, site, storage and resolver records, or <code>/bids</code> for bid history.</p>'),
  api('get-auctions','DNS auctions','Network','/api/ton/dns/auctions?tld=ton','<p>Current domain auctions. Select <code>ton</code> or <code>t.me</code>.</p>'),
  api('get-dns-expiring','Expiring domains','Accounts','/api/ton/address/:address/dns-expiring','<p>Returns domains approaching expiry. The optional <code>period</code> is the number of days before expiry.</p>'),
  api('get-staking-pool','Staking pool','Network','/api/ton/staking-pool/:address','<p>Pool stake, nominators, cycle, implementation and annual percentage yield. Append <code>/history</code> for observed APY history.</p>'),
  api('get-extra-currency','Extra currency','Assets','/api/ton/extra-currency/:id','<p>Currency ID, symbol, decimals and image.</p>'),
  api('get-extra-currency-history','Extra currency history','Accounts','/api/ton/address/:address/extra-currency/:id/history?limit=24','<p>Account events for the selected currency. Continue with <code>before_lt</code>.</p>'),
  api('get-block-boc','Block BOC','Network','/api/ton/block/:id/boc','<p>Downloads the block as a binary Bag of Cells.</p>'),
  api('get-config-raw','Raw configuration','Network','/api/ton/config/raw','<p>Raw network configuration. Add <code>master_seqno</code> to request a historical masterchain configuration.</p>'),
  api('get-config','Blockchain configuration','Network','/api/ton/config','<p>Returns decoded blockchain configuration parameters. Add <code>master_seqno</code> for a historical masterchain configuration.</p>'),
  api('get-rates','GRAM exchange rates','Network','/api/ton/rates','<p>Returns GRAM rates in AUD, CAD, CHF, EUR, GBP, JPY and USD.</p>'),
  {type:'category',title:'Transactions and messages'},
  api('get-transaction','Transaction details','Transactions','/api/ton/tx/:hash','<p>Returns the account transaction, messages, fees, phases and state changes, plus available trace and interpreted event details. <code>relatedUnavailable</code> identifies related sections that could not be loaded.</p>'),
  api('get-message','Transaction by message hash','Messages','/api/ton/message/:hash','<p>Finds the transaction associated with the supplied message hash.</p>'),
  api('get-trace','Trace','Messages','/api/ton/trace/:hash','<p>Returns the linked transaction tree with child traces and execution details.</p>'),
  api('resolve','Resolve search input','Search','/api/ton/resolve?value=:input','<p>Resolves a TON account, NFT, collection, jetton, transaction, message hash, block identifier or .ton domain. Returns the entity type and identifier.</p>'),
  {type:'category',title:'Accounts and contracts'},
  api('get-account','Account details','Accounts','/api/ton/address/:address','<p>Returns balance, status, contract interfaces, available blockchain state and DNS names. State can include code, data, storage information and extra currencies.</p>'),
  api('get-account-transactions','Account transactions','Accounts','/api/ton/address/:address/transactions?limit=24','<p>Lists account transactions. Continue with <code>before_lt=_paging.nextBeforeLt</code>; <code>after_lt</code> is also accepted.</p>'),
  api('get-account-events','Account transfers and events','Accounts','/api/ton/address/:address/events?limit=24','<p>Returns interpreted actions and their statuses. Continue with <code>before_lt</code>.</p>'),
  api('get-account-jettons','Jetton balances','Accounts','/api/ton/address/:address/jettons','<p>Returns balances with master-contract metadata and the account’s jetton-wallet addresses.</p>'),
  api('get-account-nfts','Account NFTs','Accounts','/api/ton/address/:address/nfts?limit=24&offset=0','<p>Returns NFT items, including recognized indirect sale ownership by default. Filter with <code>collection</code>, or use <code>indirect_ownership=false</code> for direct ownership only. Continue with <code>offset=_paging.nextOffset</code>.</p>'),
  api('get-account-nft-history','NFT operations','Accounts','/api/ton/address/:address/nft-history?limit=24','<p>Returns the account’s NFT operations. Continue with <code>before_lt</code>.</p>'),
  api('get-account-jetton-history','Jetton history','Accounts','/api/ton/address/:address/jetton-history?limit=24','<p>Returns jetton events for the account. Continue with <code>before_lt</code>.</p>'),
  api('get-inspect','Contract inspection','Contracts','/api/ton/address/:address/inspect','<p>Returns available contract inspection details and recognized interfaces.</p>'),
  api('get-method','Read a contract method','Contracts','/api/ton/address/:address/methods/:name','<p>Executes a read-only getter. Supply each argument as a repeated <code>args</code> parameter, for example <code>?args=123&args=456</code>. Arguments remain strings and may contain integer, address or BOC values accepted by the method.</p>'),
  api('get-staking','Staking pools','Accounts','/api/ton/address/:address/staking','<p>Returns the account’s nominator-pool positions.</p>'),
  api('get-multisig','Multisig contract','Contracts','/api/ton/address/:address/multisig','<p>Returns the multisig contract’s threshold, signers, proposers, sequence number and orders. Use the plural route below to find multisigs associated with a signer’s wallet.</p>'),
  api('get-multisigs','Multisig records','Accounts','/api/ton/address/:address/multisigs','<p>Returns multisig records associated with the account.</p>'),
  api('get-subscriptions','Subscriptions','Accounts','/api/ton/address/:address/subscriptions','<p>Returns the account’s subscription records.</p>'),
  api('get-defi','DeFi assets','Accounts','/api/ton/address/:address/defi','<p>Returns recognized DeFi positions and assets for the account.</p>'),
  {type:'category',title:'NFTs and jettons'},
  api('get-nft','NFT item','NFTs','/api/ton/nft/:address','<p>Returns the item’s owner, collection, metadata, media previews, trust and sale fields. <code>indexVerified</code> indicates whether <code>index</code> was confirmed by <code>get_nft_data</code>; the original index remains in <code>indexed_index</code>.</p>'),
  api('get-sbt','Soulbound NFT details','NFTs','/api/ton/nft/:address/sbt','<p>For a soulbound NFT, returns the authority address and revocation timestamp from its contract. A zero revocation timestamp means not revoked. Soulbound items are non-transferable.</p>'),
  api('get-nft-history','NFT history','NFTs','/api/ton/nft/:address/history?limit=24','<p>Returns events for an individual NFT. Continue with <code>before_lt</code>.</p>'),
  api('get-collection','Collection details','NFTs','/api/ton/collection/:address','<p>Returns the collection’s owner, content, metadata and previews. When <code>indexVerified</code> is true, <code>next_item_index</code> is confirmed by the collection getter; it is not necessarily a total item count.</p>'),
  api('get-collection-items','Collection items','NFTs','/api/ton/collection/:address/items?limit=24&offset=0','<p>Returns NFT items from a collection. Continue with <code>offset=_paging.nextOffset</code>.</p>'),
  api('get-jetton','Jetton details','Jettons','/api/ton/jetton/:address','<p>Returns master-contract metadata, total supply, administration, decimals and holder count.</p>'),
  api('get-jetton-holders','Jetton holders','Jettons','/api/ton/jetton/:address/holders?limit=24&offset=0','<p>Returns holder entries under <code>addresses</code>. Continue with <code>offset=_paging.nextOffset</code>. Balance values use the jetton’s decimals.</p>'),
];
export const tonWebsocketData: TonDocItem[] = [
  {type:'category',title:'Live block updates'},
  {type:'entry',fragment:'websocket-connect',title:'Connect','category':'Connection',description:'<p>Connect to the same host at <code>/api/v1/ws</code> and send <code>init</code> for the current snapshot. Basechain blocks are selected by default. Add <code>?workchain=-1</code> for the masterchain, or <code>?workchain=0&amp;shard=...</code> for a basechain shard. Use the REST API for individual accounts, NFTs, transactions and traces.</p>',request:`const socket = new WebSocket('wss://ton.tx.taxi/api/v1/ws');
socket.addEventListener('open', () => {
  socket.send(JSON.stringify({ action: 'init' }));
});
socket.addEventListener('message', event => {
  const snapshot = JSON.parse(event.data);
  if (snapshot.ton) console.log(snapshot.ton.head);
});`},
  {type:'entry',fragment:'websocket-init',title:'Current snapshot',category:'Messages',description:'<p>The response includes recent normalized <code>blocks</code> from the selected workchain and shard, plus a <code>ton</code> object with the head, observed history, observation time and stale state. Use <code>ton.head</code> for complete selected-block fields and <code>ton.masterchainHead</code> for the network masterchain head. Send <code>{"action":"select","workchain":-1}</code> to switch an open connection to the masterchain.</p>',request:'{"action":"init"}'},
  {type:'entry',fragment:'websocket-ping',title:'Keep the connection active',category:'Messages',description:'<p>Send a ping to check the connection. On reconnect, send <code>init</code> again to obtain the current snapshot.</p>',request:'{"action":"ping"}',response:'{"pong":true}'},
  guide('websocket-stale','Delayed updates','State','<p>When <code>ton.stale</code> is true, retain the last available blocks and mark them as delayed. <code>ton.observedAt</code> is the observation timestamp. WebSocket connection health alone does not establish data freshness.</p>'),
];
